version: "3.4"
services:
  golang:
    container_name: golang
    image: app1/golang:1.0.0
    build: .
    volumes:
      - .:/go/src/work/
    ports:
      - 8080:8080
    depends_on:
      - db
 db:
   image: postgres
   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres